### ISSUE TITLE
Dynamic iconURLs

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph-extension-api#10]
Being able to set the iconURL dynamically would let CXP extensions gray out their icon when toggled (e.g. Codecov), show little badges, or show a red X to draw the user's attention to a bad setting (e.g. API token).

**Comment by sqs** [comment]
You can set dynamic contributions. It’s probably going to cause UI jitter and needs some work there, but it’s possible. 

Check the cxp-sample-wip branch ./cxp/cmd/cx-sample-bundle-sandbox for an example.

**Comment by sqs** [comment]
This was working in sourcegraph-codecov by supplying an SVG with template exprs. I removed it for simplicity, but it's possible.
