### ISSUE TITLE
RegExp constructor fails to function as expected?

### ISSUE THREAD

**Issue by danielevan** [sourcegraph/sourcegraph-extension-api#115]
#### Writing a Sourcegraph extension in typescript, "new RegExp ('')" constructor fails to produce something usable like the "/ /;" regexp builder. 

Is it there additional configuration required to be able to call "new RegeExp ('')" in your extension

**Comment by chrismwendt** [comment]
Extensions are plain JavaScript, so `new RegExp()` works just like it does in any other browser context. What problem are you running into? Can you post what you tried, what the result was, and what you expected?

**Comment by danielevan** [comment]
Oops - File under "nevermind", it was user error ;)
