### ISSUE TITLE
Google Cloud API - anyone publishing extensions that employ it?

### ISSUE THREAD

**Issue by danielevan** [sourcegraph/sourcegraph-extension-api#116]
#### I attempt to publish code that calls the Translate constructor - 

`import { Translate } from 'google-cloud/translate';`
`  // Instantiate a client`
`  const translate = new Translate({projectId: 'my-project-id' });`

#### `src ext publish` fails:

> npm WARN deprecated google-cloud@0.58.2: The google-cloud package has been deprecated. We strongly recommend installing individual API packages, such as @google-cloud/storage. For a list of Google Cloud Platform API specific packages please visit https://cloud.google.com/nodejs/docs/reference/libraries
> 
> \> google-cloud@0.58.2 preinstall /Users/dan/IdeaProjects/sourcegraph-lionize/node_modules/google-cloud
> \> node scripts/preinstall.js
> 
> The google-cloud package has been deprecated. We stronglyrecommend installing individual API packages, such as @google-cloud/storage. For a list of Google Cloud Platform API specific packages please visit https://cloud.google.com/nodejs/docs/reference/libraries
> npm WARN sourcegraph-lionize@ No repository field.
> npm WARN sourcegraph-lionize@ No license field.
> 
> 

> npm ERR! code ELIFECYCLE
> npm ERR! errno 255
> npm ERR! google-cloud@0.58.2 preinstall: `node scripts/preinstall.js`
> npm ERR! Exit status 255
> npm ERR! 
> npm ERR! Failed at the google-cloud@0.58.2 preinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I'm able to execute the attached javascript file using the `node` command line tool and don't get any such warnings or errors. 

The license in this case comes from the file specified by the environmental variable `GOOGLE_APPLICATION_CREDENTIALS` (JSON file that contains a private key).  One would want to prevent the plaintext dissemination of these private keys to all client browsers; does a strategy exist for client-side execution when private keys are needed?
[translate.js.txt](https://github.com/sourcegraph/sourcegraph-extension-api/files/2527308/translate.js.txt)

**Comment by chrismwendt** [comment]
I think the warning is telling you to:

```
yarn remove google-cloud
yarn add @google-cloud/translate
```

```diff
-import { Translate } from 'google-cloud/translate';
+import { Translate } from '@google-cloud/translate';
```

Does that work? This is not specific to Sourcegraph extensions, it's a package management issue.

Whatever you put into your Sourcegraph extension JS bundle will be visible to everyone (it's a public URL). You can instruct the user to add their own private key to their user settings in Sourcegraph, and read that value at runtime in your Sourcegraph extension. A user's settings are visible to any extension that user enables.

**Comment by danielevan** [comment]
Many thanks!  

The user will be instructed to [acquire and place a key file](https://cloud.google.com/storage/docs/reference/libraries#setting_up_authentication) from Google Cloud.  In [Google's sample code](https://github.com/googleapis/nodejs-translate/blob/master/system-test/translate.ts) they refer to this key file with 

`const API_KEY = process.env.TRANSLATE_API_KEY;`

**Comment by danielevan** [comment]
Package management - I have a couple of questions if I may - 

First: yarn vs npm?  Any prevailing choice?   If yarn do we remove package-lock.json?

Second: guessing this is something simple I'm missing - 
 attempting to access google-cloud/translate.  My package.json includes:
```
  "dependencies": {
    "@google-cloud/translate": "^2.1.2",
    "rxjs": "^6.3.3"
  }
```
My code states `import { Translate } from '@google-cloud/translate` and I instantiate a client as above.

I run `rm -rf node_modules && yarn install` and all goes well (except a couple warnings about No license field and it complains about package-lock.json). 

The output of `src ext publish`:
```
Dans2015iMac:sourcegraph-lionize dan$ src ext publish
# sourcegraph:prepublish: parcel build --no-minify src/extension.ts
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@google-cloud/translate/build/src/index.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@google-cloud/translate/build/src/index.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@google-cloud/common/build/src/index.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@google-cloud/common/build/src/index.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/teeny-request/build/src/index.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/teeny-request/build/src/index.js".
⚠️  Could not load source file "../../src/util.ts" in source map of "../node_modules/@google-cloud/common/build/src/util.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/google-auth-library/build/src/index.js".
⚠️  Could not load source file "../../../src/auth/computeclient.ts" in source map of "../node_modules/google-auth-library/build/src/auth/computeclient.js".
⚠️  Could not load source file "../../../src/auth/jwtclient.ts" in source map of "../node_modules/google-auth-library/build/src/auth/jwtclient.js".
⚠️  Could not load source file "../../src/transporters.ts" in source map of "../node_modules/google-auth-library/build/src/transporters.js".
🚨  /Users/dan/IdeaProjects/sourcegraph-lionize/node_modules/google-auth-library/build/src/auth/jwtclient.js: Property name expected type of string but got null
    at validate (/Users/dan/IdeaProjects/sourcegraph-lionize/node_modules/@babel/types/lib/definitions/utils.js:161:13)
    at Object.validate (/Users/dan/IdeaProjects/sourcegraph-lionize/node_modules/@babel/types/lib/definitions/utils.js:172:7)
    at validate (/Users/dan/IdeaProjects/sourcegraph-lionize/node_modules/@babel/types/lib/validators/validate.js:17:9)
    at builder (/Users/dan/IdeaProjects/sourcegraph-lionize/node_modules/@babel/types/lib/builders/builder.js:46:27)
    at Object.Identifier (/Users/dan/IdeaProjects/sourcegraph-lionize/node_modules/@babel/types/lib/builders/generated/index.js:316:31)
    at /Users/dan/IdeaProjects/sourcegraph-lionize/node_modules/regenerator-transform/lib/hoist.js:30:29
    at Array.forEach (<anonymous>)
    at varDeclToExpr (/Users/dan/IdeaProjects/sourcegraph-lionize/node_modules/regenerator-transform/lib/hoist.js:27:23)
    at exit (/Users/dan/IdeaProjects/sourcegraph-lionize/node_modules/regenerator-transform/lib/hoist.js:46:20)
    at NodePath._call (/Users/dan/IdeaProjects/sourcegraph-lionize/node_modules/@babel/traverse/lib/path/context.js:53:20)
sourcegraph:prepublish script failed: exit status 1 (see output above)

```

**Comment by chrismwendt** [comment]
I'd recommend yarn, and yes delete `package-lock.json`.

I wish I could be of more help with the `@google-cloud` error, but I don't know what's going wrong. You could try setting it up in a fresh repo with no other dependencies and debug from there.

**Comment by slimsag** [comment]
I may be completely wrong here, but https://www.npmjs.com/package/@google-cloud/translate explicitly mentions Node.js -- doesn't that imply it could rely on Node.js system APIs that are not available in the web?

**Comment by danielevan** [comment]
Given that, might it be better to avoid the Node.js offering and instead refer to their [REST API](https://cloud.google.com/translate/docs/reference/rest)?

https://cloud.google.com/translate/docs/reference/rest

**Comment by slimsag** [comment]
I'm not positive, but yeah, I think you should use https://cloud.google.com/translate/docs/quickstart

**Comment by danielevan** [comment]
Thanks!  Indeed using `curl` to `POST` to `https://translation.googleapis.com/language/translate/v2` behaves as expected.  

The jump to Node.JS is where it bogged down.  Since the REST API is working I'll go forward with that.
