### ISSUE TITLE
Syntax checking of .ts files - any tips?

### ISSUE THREAD

**Issue by danielevan** [sourcegraph/sourcegraph-extension-api#118]
#### Syntax errors in .ts files - how does a developer best catch them? 

I've had syntax errors pass through `src ext publish` without any warning.  When the browser loads the extension with a syntax error on the client side, the .js appears then disappears very quickly in the developer console.    This arrangement means the developer has to find syntax errors by carefully reading all the code. 

Is there a good way to check the syntax of your TypeScript code?  Guessing `tsc` should help, at the moment I'm seeing if I can put together a tsconfig.json that works for my extension.  Is there a good template?

**Comment by nicksnyder** [comment]
Compiling TypeScript should catch all errors if you have it configured correctly. Here are some examples of other Sourcegraph extensions: https://github.com/sourcegraph/sourcegraph-extension-docs/blob/master/docs/early_adopters.md

**Comment by danielevan** [comment]
Got it working thx :)
