### ISSUE TITLE
Alternative to dynamic imports in a Sourcegraph extentsion?

### ISSUE THREAD

**Issue by jlangston** [sourcegraph/sourcegraph-extension-api#119]
#### Question description

Has anyone used dynamic import statements inside of any existing Sourcegraph extension?

#### Is your question related to a problem? If so, please describe or link to another issue.

Trying to use `import()` statements in an extension with parcel I ran across the issue 

``` TypeError: Module scripts are not supported on WorkerGlobalScope yet (see https://crbug.com/680046)```

Is there an alternative recommended way I could bundle the extension to be able use `importScripts` instead?

#### Additional context

My specific use case is trying to import individual rule definitions from tslint like 
```import(`tslint/lib/rules/${ruleName}Rule`)```

Including every rule as a static import looks to work when bundling but I'm hitting an issue in sourcegraph itself where it seems like it won't run the extension code and I don't get an error as well as bloating the extension file size.

**Comment by sqs** [comment]
(This is blocking #97.)

I’m not aware of any extensions built yet that use dynamic imports. I wish I could be more helpful. Is this the same problem as https://github.com/parcel-bundler/parcel/issues/112? If so, you could try using Webpack instead.

**Comment by ijsnow** [comment]
I'd have to look at how extensions are served but I'm not sure we'd be able to use dynamic import statements. From my understanding, (*) extensions are just a JS script that is ran in a web worker. When using dynamic imports, your application or script isn't compiled into one file, its built into a static bundle(directory) to  be served on an as needed basis. 

(*) Is my understanding correct @chrismwendt @sqs?

**Comment by felixfbecker** [comment]
I wonder if we could rethink our extensions to not rely on bundles at all but use native ES module imports (with bundling being optional)

**Comment by jlangston** [comment]
Taking a step back and looking at my approach with the extension. I don't think I'll actually end up needing dynamic imports in the extension explicitly as I think it makes more sense to move the analysis portion into a server component to be paired with the extension for the actual analysis.  

Thank you all for your input.
