### ISSUE TITLE
Don't swallow error message when createMessageTransports fails

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph-extension-api#13]
When [createMessageTransports](https://sourcegraph.com/github.com/sourcegraph/cxp-js/-/blob/src/environment/controller.ts#L181:17-181:40$references) is rejected, the error message is throw away. It would be nice to keep it around so the client can display that error to the user (e.g. if a JS bundle 404s).

I think this would involve changing the `() => ...` to `e => ...` at https://sourcegraph.sgdev.org/github.com/sourcegraph/cxp-js@9baa81d/-/blob/src/client/client.ts#L168 and changing the `ClientState` type from an enum to something like `ClientState | Error`.

**Comment by slimsag** [comment]
Given this is referencing a no longer used library, I am closing this.
