### ISSUE TITLE
Registering capabilities and listening to requests could be simplified

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph-extension-api#34]
The two calls `sendRequest(RegistrationRequest.type, ...)` followed by `onRequest(...)` are redundant because it's useless to register (e.g. a hover provider) but not add a listener.

https://github.com/sourcegraph/cx-hello-world-hover/blob/a109acf36ecb92a86a1dca53f269ce5f640f883f/src/extension.ts

```typescript
    await cxp.rawConnection.sendRequest(RegistrationRequest.type, {
        registrations: [
            {
                id: HoverRequest.type.method,
                method: HoverRequest.type.method,
                registerOptions: { documentSelector: ['*'] },
            },
        ],
    })

    // Start responding to hover tooltip requests.
    cxp.rawConnection.onRequest(HoverRequest.type.method, () => ({
        contents: '👋 Hello from an extension!',
    }))
```

These two calls could be merged into one `addListener(...)` call (just like DOM events) which automatically registers and deregisters the capability.

```typescript
const listener = cxp.addListener('hover', pos => ...)
```

`cxp.removeListener(listener)` could also be supported.

**Comment by slimsag** [comment]
I am closing this because it looks unrelated to the new extensions API.
