### ISSUE TITLE
All common features (like hovers) should have dedicated methods

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph-extension-api#36]
When an author has to write `connection.send{Request,Notification}` and pass in the method, it feels more like a protocol and less like an API.

Aliases like `onHover()` or `publishDecorations()` will enable authors to more easily explore the API via autocomplete in their editor and make extension code more readable.

**Comment by slimsag** [comment]
@chrismwendt Is this still an issue? I haven't seen things like the API you are describing here in extensions. I assume it is from the old protocol?

**Comment by sqs** [comment]
This is from the old protocol
