### ISSUE TITLE
Document how to create extensions

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph-extension-api#42]
The extension authoring experience is undocumented. We intend to write very good tutorials and publish our API docs soon.

High-level:

> Writing a Sourcegraph extension is very similar to writing an editor extension for [VS Code](https://code.visualstudio.com/docs/extensions/overview). See the [Codecov extension's main `extension.ts` file](https://sourcegraph.sgdev.org/github.com/sourcegraph/sourcegraph-codecov/-/blob/src/extension.ts) for an example.

Subscribe to this issue to get notified when extension authoring docs exist.

**Comment by ryan-blunden** [comment]
[Sourcegraph extension Hello World tutorial](https://github.com/sourcegraph/sourcegraph-extension-docs/blob/master/tutorials/hello-world.md) now available.

**Comment by ryan-blunden** [comment]
Repository for [Sourcegraph extension samples](https://github.com/sourcegraph/sourcegraph-extension-samples/) created, featuring a great example by @chrismwendt showing [token selection and line decoration](https://github.com/sourcegraph/sourcegraph-extension-samples/tree/master/token-highlights).

**Comment by felixfbecker** [comment]
Can the README be updated then and this issue closed?
