### ISSUE TITLE
Extension authoring feedback

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph-extension-api#43]
From @felixfbecker:

Some feedback on working with the extension stuff for the first time. All these points are minor and I could probably all resolve them if I just dig deeper, but all the points together already costed me a lot of time. I hope we can resolve most of these (i.e. better documentation and team education) since more people will run into this. For context, this was to investigate a P1 regression reported by a user: https://github.com/sourcegraph/issues/issues/138

- [x] ~~~The platform flag is on in production, but not in local dev, which in this case meant the issue didn’t appear locally. I had to remember to turn on the feature flag locally (I first had just cleared local storage).~~~ fixed
- I didn’t know where LSP stuff now comes from (i.e. where is the code?) which made it hard to debug, since providers are now dynamic. I have no idea at what layer in extensions-api I could add the validation.
- [x] ~~~I also couldn’t easily trace it because the extension API didn’t publish sourcemaps properly~~~ fixed https://github.com/sourcegraph/sourcegraph/pull/13129
- https://github.com/sourcegraph/sourcegraph-extension-api/issues/44
- I tried syncing changes in lib/ to the web app but that didn’t work initially, because the extension API builds multiple module targets, and the files we use are actually in module/ (relates to the point above, because I didn’t see the folder)
- I wasn’t aware that `sourcegraph` (npm package) is also depended on by @sourcegraph/extensions-client-common, and hovers will actually go through that package. This caused me to sync changes to the wrong package at first
- [x] ~~~After this, I could still not trace the call because apparently the extension also doesn’t contain proper sourcemaps. I couldn’t fix that because I don’t know where it is, which was the point of tracing it…~~~ fixed https://github.com/sourcegraph/sourcegraph/pull/13129
- I searched for repos in the sourcegraph org and found `sourcegraph-langserver-http` and guessed that could be it (even though I first thought it was an HTTP langserver)
- [x] ~~~I did a PR: https://github.com/sourcegraph/sourcegraph-langserver-http/pull/4~~~ merged
- [ ] I don’t know how I would deploy that change, or where to look to find out -- *awaiting reply in https://github.com/sourcegraph/sourcegraph-langserver-http/pull/4#issuecomment-418949238*

**Comment by felixfbecker** [comment]
Maybe we can make `npm link` work, otherwise I would have just needed better documentation (and in a place where one could find it, i.e. linked from the main repo docs)
