### ISSUE TITLE
Create a sourcegraph extension generator (yarn create sourcegraph-extension)

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph-extension-api#77]
This can be a fork of https://github.com/sourcegraph/create

**Comment by slimsag** [comment]
This would've helped me. The code discussions extension I created following the hello world tutorial has no linting, uses TypeScript but doesn't appear to receive any type-checking, etc.

**Comment by ryan-blunden** [comment]
WIP at https://github.com/sourcegraph/create-extension

**Comment by slimsag** [comment]
@ryan-blunden this is done, yes?

**Comment by sqs** [comment]
Yes
